#include "zig.h"
zig_extern int32_t add(int32_t const a0, int32_t const a1);
zig_extern unsigned long RemoveVectoredExceptionHandler(void *const a0);
zig_extern zig_noreturn void ExitProcess(unsigned int const a0);
zig_extern void *CreateToolhelp32Snapshot(uint32_t const a0, uint32_t const a1);
zig_extern uint16_t GetLastError(void);
zig_extern int Module32First(void *const a0, struct MODULEENTRY32__4326 *const a1);
zig_extern int Module32Next(void *const a0, struct MODULEENTRY32__4326 *const a1);
zig_extern void *GetCurrentProcess(void);
zig_extern uint32_t K32GetModuleFileNameExW(void *const a0, void *const a1, uint16_t *const a2, uint32_t const a3);
zig_extern uint32_t NtCreateSection(void **const a0, uint32_t const a1, struct OBJECT_ATTRIBUTES__5656 *const a2, int64_t *const a3, uint32_t const a4, uint32_t const a5, void *const a6);
zig_extern uint32_t NtMapViewOfSection(void *const a0, void *const a1, void **const a2, uint32_t *const a3, uintptr_t const a4, int64_t *const a5, uintptr_t *const a6, int32_t const a7, uint32_t const a8, uint32_t const a9);
zig_extern uint32_t NtUnmapViewOfSection(void *const a0, void *const a1);
zig_extern void RtlCaptureContext(struct CONTEXT__7060 *const a0);
zig_extern void AcquireSRWLockExclusive(struct SRWLOCK__2666 *const a0);
zig_extern uint32_t GetCurrentThreadId(void);
zig_extern uint32_t FormatMessageW(uint32_t const a0, void *const a1, uint16_t const a2, uint32_t const a3, uint16_t *const a4, uint32_t const a5, void **const a6);
zig_extern uint32_t NtClose(void *const a0);
zig_extern int GetConsoleScreenBufferInfo(void *const a0, struct CONSOLE_SCREEN_BUFFER_INFO__7730 *const a1);
zig_extern uint32_t RtlGetFullPathName_U(uint16_t const *const a0, uint32_t const a1, uint16_t *const a2, uint16_t const **const a3);
zig_extern int SetConsoleTextAttribute(void *const a0, uint16_t const a1);
zig_extern struct RUNTIME_FUNCTION__8202 *RtlLookupFunctionEntry(uint64_t const a0, uint64_t *const a1, struct UNWIND_HISTORY_TABLE__8200 *const a2);
zig_extern int32_t (**RtlVirtualUnwind(uint32_t const a0, uint64_t const a1, uint64_t const a2, struct RUNTIME_FUNCTION__8202 *const a3, struct CONTEXT__7060 *const a4, void **const a5, uint64_t *const a6, struct KNONVOLATILE_CONTEXT_POINTERS__8205 *const a7))(struct EXCEPTION_RECORD__8206 *, void *, struct CONTEXT__7060 *, void *);
zig_extern void ReleaseSRWLockExclusive(struct SRWLOCK__2666 *const a0);
zig_extern int GetConsoleMode(void *const a0, uint32_t *const a1);
zig_extern uint32_t NtLockFile(void *const a0, void *const a1, void (**const a2)(void *, struct IO_STATUS_BLOCK__8356 *, uint32_t), void *const a3, struct IO_STATUS_BLOCK__8356 *const a4, int64_t const *const a5, int64_t const *const a6, uint32_t *const a7, uint8_t const a8, uint8_t const a9);
zig_extern uint16_t RtlUpcaseUnicodeChar(uint16_t const a0);
zig_extern int GetFileSizeEx(void *const a0, int64_t *const a1);
zig_extern int ReadFile(void *const a0, uint8_t *const a1, uint32_t const a2, uint32_t *const a3, struct OVERLAPPED__8443 *const a4);
zig_extern uint32_t RtlWaitOnAddress(void const *const a0, void const *const a1, uintptr_t const a2, int64_t const *const a3);
zig_extern void *VirtualAlloc(void *const a0, uintptr_t const a1, uint32_t const a2, uint32_t const a3);
zig_extern int VirtualFree(void *const a0, uintptr_t const a1, uint32_t const a2);
zig_extern uint32_t NtQueryVolumeInformationFile(void *const a0, struct IO_STATUS_BLOCK__8356 *const a1, void *const a2, uint32_t const a3, int32_t const a4);
zig_extern uint32_t NtQueryInformationFile(void *const a0, struct IO_STATUS_BLOCK__8356 *const a1, void *const a2, uint32_t const a3, int32_t const a4);
zig_extern uint32_t NtCreateFile(void **const a0, uint32_t const a1, struct OBJECT_ATTRIBUTES__5656 *const a2, struct IO_STATUS_BLOCK__8356 *const a3, int64_t *const a4, uint32_t const a5, uint32_t const a6, uint32_t const a7, uint32_t const a8, void *const a9, uint32_t const a10);
zig_extern int SetFilePointerEx(void *const a0, int64_t const a1, int64_t *const a2, uint32_t const a3);
zig_extern int WriteFile(void *const a0, uint8_t const *const a1, uint32_t const a2, uint32_t *const a3, struct OVERLAPPED__8443 *const a4);
zig_extern uint8_t RtlEqualUnicodeString(struct UNICODE_STRING__5657 const *const a0, struct UNICODE_STRING__5657 const *const a1, uint8_t const a2);
zig_extern void Sleep(uint32_t const a0);
